name: Chain endpoints
on:
  push:
    branches:
      - development
      - main
  #schedule:
    # twice daily (mornings/afternoons, the latter being busy)
    # - cron:  '50 0/12 * * *'
    # once daily (early mornings, 02:50 GMT, generally not busy)
  #  - cron:  '50 2 * * *'

jobs:
  endpoints:
    if: github.repository == 'polkadot-js/apps'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 'lts/*'
    - name: check
      env:
        CI_LOG: 123
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ci:chainEndpoints

    - name: issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/chain-endpoints.md
        update_existing: true
